@Platform.WebInstaller_HostAddress = http://localhost:5283

GET {{Platform.WebInstaller_HostAddress}}/install/status
Accept: application/json

###

POST {{Platform.WebInstaller_HostAddress}}/install/test-database
Content-Type: application/json

{
  "host": "localhost",
  "port": 1433,
  "databaseName": "WhiteLabelErp",
  "username": "sa",
  "password": "YourStrong!Passw0rd",
  "trustServerCertificate": true
}

###
